### ISSUE TITLE
unable to install SyMPC 

### ISSUE THREAD

**Issue by saichandrapandraju** [OpenMined/SyMPC#265]
## Question
**Describe your question in ONE SENTENCE.**

Unable to install SyMPC though I have installed all the required dependencies.

## Further Information
Describe your question in greater length here.

I'm trying out Model Centric Federated Learning using PySyft and PyGrid. While doing so I got `ModuleNotFoundError: No module named 'sympc'` error. 
For installing sympc, as I had all dependencies installed, I downloaded this repo and ran `pip install .` and I'm getting an error and here is the trace - 
```
 DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\saichandra.pandraju\.conda\envs\pysyft_fl_dp\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\saichandra.pandraju\\AppData\\Local\\Temp\\pip-req-build-qxhncasy\\setup.py'"'"'; __file__='"'"'C:\\Users\\saichandra.pandraju\\AppData\\Local\\Temp\\pip-req-build-qxhncasy\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\saichandra.pandraju\AppData\Local\Temp\pip-pip-egg-info-lydd_p75'
         cwd: C:\Users\saichandra.pandraju\AppData\Local\Temp\pip-req-build-qxhncasy\
    Complete output (29 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\saichandra.pandraju\AppData\Local\Temp\pip-req-build-qxhncasy\setup.py", line 24, in <module>
        setup(use_pyscaffold=True)
      File "C:\Users\saichandra.pandraju\.conda\envs\pysyft_fl_dp\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\saichandra.pandraju\.conda\envs\pysyft_fl_dp\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Users\saichandra.pandraju\.conda\envs\pysyft_fl_dp\lib\site-packages\setuptools\dist.py", line 432, in __init__
        _Distribution.__init__(self, {
      File "C:\Users\saichandra.pandraju\.conda\envs\pysyft_fl_dp\lib\distutils\dist.py", line 292, in __init__
        self.finalize_options()
      File "C:\Users\saichandra.pandraju\.conda\envs\pysyft_fl_dp\lib\site-packages\setuptools\dist.py", line 708, in finalize_options
        ep(self)
      File "C:\Users\saichandra.pandraju\.conda\envs\pysyft_fl_dp\lib\site-packages\setuptools\dist.py", line 715, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "c:\users\saichandra.pandraju\appdata\local\temp\pip-req-build-qxhncasy\.eggs\pyscaffold-3.2.3-py3.9.egg\pyscaffold\integration.py", line 105, in pyscaffold_keyword
        version_keyword(dist, keyword, setuptools_scm_config(value))
      File "c:\users\saichandra.pandraju\appdata\local\temp\pip-req-build-qxhncasy\.eggs\pyscaffold-3.2.3-py3.9.egg\pyscaffold\contrib\setuptools_scm\integration.py", line 17, in version_keyword
        dist.metadata.version = get_version(**value)
      File "c:\users\saichandra.pandraju\appdata\local\temp\pip-req-build-qxhncasy\.eggs\pyscaffold-3.2.3-py3.9.egg\pyscaffold\contrib\setuptools_scm\__init__.py", line 150, in get_version
        parsed_version = _do_parse(config)
      File "c:\users\saichandra.pandraju\appdata\local\temp\pip-req-build-qxhncasy\.eggs\pyscaffold-3.2.3-py3.9.egg\pyscaffold\contrib\setuptools_scm\__init__.py", line 105, in _do_parse
        raise LookupError(
    LookupError: setuptools-scm was unable to detect version for 'C:\\Users\\saichandra.pandraju\\AppData\\Local\\Temp\\pip-req-build-qxhncasy'.

    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    ----------------------------------------
WARNING: Discarding file:///C:/Users/saichandra.pandraju/Desktop/federated_demo/SyMPC-main. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Here are the related dependencies that I have - 
`sycret==0.1.3`
`syft==0.5.0`
`torch==1.8.1`
`torchcsprng==0.2.1`

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS: Windows
 - OS Version: 10
 - Language Version: Python 3.9
 - Package Manager Version: Conda 4.9.2

**Comment by aanurraj** [comment]
can you run `pip install -e .`

**Comment by anshpujara14** [comment]
Hi! I tried the above steps but still not able to download SyMPC. 
I rand the command `pip install -e .` but it is giving me this error:
`ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.`
Any idea how can I solve this?

**Comment by stevenjgore** [comment]
I also am having this issue when trying to install on a raspberry pi 4b. 
running "pip install -e ." did not solve the issue for me and I got the same error message.

can SyMPC be installed on an ARM processor?

**Comment by Cryptographer63** [comment]
> processor
My computer is also macos version m1 and I have the same problem

**Comment by Cryptographer63** [comment]
> I also am having this issue when trying to install on a raspberry pi 4b. running "pip install -e ." did not solve the issue for me and I got the same error message.
> 
> can SyMPC be installed on an ARM processor?

My computer is also macos version m1 and I have the same problem

**Comment by soenshen** [comment]
> > I also am having this issue when trying to install on a raspberry pi 4b. running "pip install -e ." did not solve the issue for me and I got the same error message.
> > can SyMPC be installed on an ARM processor?
> 
> My computer is also macos version m1 and I have the same problem

I also meet the problem in my Ubuntu20.0.04 virtual machine. but you can try to find the directory that includes setup.py to run the above command. however, when I finished that it still showed that 'error:no module named sympc'
